### ISSUE TITLE
Luo spingboottiin Käyttäjät ja Käyttäjälupa taulut.

### ISSUE THREAD

**Issue by cmdtvt** [Alttz/CopyPaste-ohjelmistoprojekti#18]
Tauluihin tarvittavat kentät ovat näkyvillä teamsissa.

**Comment by Alttz** [comment]
Luotu entiteetit ja niiden repositoryt.

AppUser.java
Role.java
Permission.java

Myös teams-ryhmästä löytyvä tietokanta kaavio päivitetty vastaamaan lopullista tietokantaa, joka Springbootissa luodaan.
