### ISSUE TITLE
Tarkista ja korjaa tietokantakaavion relaatiot.

### ISSUE THREAD

**Issue by cmdtvt** [Alttz/CopyPaste-ohjelmistoprojekti#27]
Tarkista tietokannan relaatiot ja päivitä kyseiset relaatiot projektiohjeessa olevaan kuvaan tietokanta osiossa.

**Comment by Alttz** [comment]
Kävin päivittämässä tämän tietokanta-kaavion ja sen relaatiot.
Päivitetty kaavio löytyy githubin projekti-ohjeesta ja sitä voi tarvittaessa muokata täällä:

https://lucid.app/lucidchart/1ad4f005-cfc3-42b5-81c7-0557df913579/edit?beaconFlowId=4120EB49004C31BA&invitationId=inv_125d3f29-39d6-4011-aaac-fe40a60c8332&page=0_0#
