### ISSUE TITLE
(REST API) Hae tapahtumia

### ISSUE THREAD

**Issue by Tohvudev** [Alttz/CopyPaste-ohjelmistoprojekti#30]

**Comment by Alttz** [comment]
Tähän luotu jo GET-metodi, joka hakee kaikki tapahtumat /events endpointista.

**Comment by Alttz** [comment]
Luotu GET-metodit, jolla tapahtumia voi hakea eri kriteerein.

Hae kaikki tapahtumat
- http://localhost:8080/events

Hae tapahtuma id:n perusteella

- http://localhost:8080/event/1

Hae tapahtumat kaupungin perusteella

- http://localhost:8080/events/search/byName?name=TapahtumanNimi

Hae tapahtumat tapahtuman nimen perusteella

- http://localhost:8080/events/search/byCity?city=KaupunginNimi
