### ISSUE TITLE
Hakuominaisuuden muutos

### ISSUE THREAD

**Issue by cmdtvt** [Alttz/CopyPaste-ohjelmistoprojekti#37]
Tunnilla opettaja ehdottin `/api/events/search/` routen poistamista.
`/api/events` riittäisi ja siihen voisi url paramentreilla passata hakutermit

esimerkiksi kun haetaan kaikki kaupungit `/api/events?byCity=helsinki`

**Comment by Alttz** [comment]
Poistettu /search/ osuus endpointeista.
