### ISSUE TITLE
Projektiohjeen pohjan luominen

### ISSUE THREAD

**Issue by cmdtvt** [Alttz/CopyPaste-ohjelmistoprojekti#8]
Dokumentaatiosta luvut Johdanto ja Järjestelmän määrittely sekä Käyttöliittymä alustavasti

**Comment by Alttz** [comment]
Linkki projekti-ohjeen .md tiedostoon: https://github.com/Alttz/CopyPaste-ohjelmistoprojekti/blob/develop/projektiohje.md

**Comment by nyDropTheC** [comment]
Lisätty branch

**Comment by Alttz** [comment]
Mergesin Nikolain tekemän uuden Haaran Developiin.

**Comment by nyDropTheC** [comment]
Taitaa olla valmiina.
