### ISSUE TITLE
Springboot pohjan luominen

### ISSUE THREAD

**Issue by cmdtvt** [Alttz/CopyPaste-ohjelmistoprojekti#9]
Spring Boot -projektin alustus GitHubiin

**Comment by Alttz** [comment]
Springboot initialized using following settings:


![Image](https://github.com/Alttz/CopyPaste-ohjelmistoprojekti/assets/66692116/4f28ad72-de93-448a-b504-712f43f5d640)

**Comment by nyDropTheC** [comment]
Saattaa tarvita lisää riippuvuuksia, mutta ne voidaan lisätä myöhemmin

**Comment by Alttz** [comment]
Jep. Kävin tuota alustusta jo laajentamassa uuteen Haaraan, mutta en lähtenyt vielä mergeemään developiin ennenkuin tietää vähän tarkemmin, että millaisia odotuksia tolle ohjelmistolle tulee olemaan.

kts. https://github.com/Alttz/CopyPaste-ohjelmistoprojekti/tree/FeatSpringbootAlustus

Veikkaan, että ens viikolla ruvetaan tarkemmin rakentamaan tuota itse palvelua.

Tollasia ajattelin ainakin, että voi kehitysvaiheessa tulla relevanteiksi:

- spring-boot-starter-web
- spring-boot-starter-thymeleaf
- spring-boot-devtools
- spring-boot-starter-data-jpa
- mariadb-java-client
- spring-boot-starter-test
- h2
